// Analytic absorption remains deterministic with full GI off. Use the same
// RGB extinction as the transport model; artwork alpha is not an optical depth.
fn bg_water_beer(path:f32)->vec3f {
 return exp(-vec3f(0.3406803136,0.0579,0.0125513234)*max(path,0.0));
}
fn bg_enhanced_water_surface(tint:vec4f,normal:vec3f,sky:f32,glow:f32,
 world:vec3f,relative:vec3f,front:bool,time:f32,sun_visibility:f32,footprint:vec4f,pixel:vec2f)->BgSceneOutput {
 let lighting=bg_water_lighting(tint,normal,sky,glow,world,relative,front,time,sun_visibility,footprint);
 var result=lighting.output;
 // Unconfigured standalone draws and underwater exit faces retain the legacy
 // transparency path. Never sample an uninitialized or mismatched snapshot.
 if bg_water_optics.properties.z<0.5 || bg_water_optics.eye.w>0.5
  || any(textureDimensions(bg_water_bed_depth)!=vec2u(bg_water_optics.properties.xy)) {return result;}
 let p=clamp(vec2i(pixel),vec2i(0),vec2i(textureDimensions(bg_water_bed_depth))-1);
 let depth=textureLoad(bg_water_bed_depth,p,0).r;
 var path=256.0;
 if depth<1.0 {
  let uv=(vec2f(p)+0.5)/bg_water_optics.properties.xy;
  let h=bg_water_optics.inverse*vec4f(uv*vec2f(2.0,-2.0)+vec2f(-1.0,1.0),depth,1.0);
  let bed=h.xyz/h.w;
  // Both points lie on the same camera ray; the signed distance rejects beds
  // in front of the surface instead of turning them into dark absorption.
  path=clamp(dot(bed-world,relative/max(length(relative),0.00001)),0.0,256.0);
 }
 let transmission=bg_water_beer(path);
 let background=textureLoad(bg_water_bed_color,p,0).rgb;
 let fog_sky=max(sky,camera.eye.w);
 let fog_transmission=bg_fog_transmittance(relative+camera.eye.xyz,fog_sky);
 let fog_color=bg_apply_fog(vec3f(0.0),relative+camera.eye.xyz,fog_sky);
 // Replace the old constant water diffuse with depth-dependent fill. The
 // snapshot already contains aerial fog: preserve that background term and
 // add fog only to energy generated by water. Reflections stay independent.
 let composed=max(result.color.rgb-lighting.diffuse*transmission*fog_transmission
  +(background-fog_color)*transmission*(1.0-lighting.fresnel),vec3f(0.0));
 result.reflection_response=vec4f(result.reflection_response.rgb/max(result.color.a,0.00001),result.reflection_response.a);
 result.color=vec4f(composed,1.0);
 return result;
}
