//! Shared voxel coordinates, deterministic terrain, and authoritative edits.

use std::collections::{BTreeMap, HashMap, HashSet};
use std::io;
use std::path::PathBuf;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Arc, Weak};

use crate::storage::{SavedEdits, Storage};

pub const CHUNK_SIZE: usize = 16;
pub const CHUNK_VOLUME: usize = CHUNK_SIZE * CHUNK_SIZE * CHUNK_SIZE;
pub const MAX_TERRAIN_HEIGHT: i32 = 64;
pub const MAX_GENERATED_HEIGHT: i32 = MAX_TERRAIN_HEIGHT + 10;
pub const BEDROCK_Y: i32 = -64;
pub const TERRAIN_GENERATOR_VERSION: u16 = 4;
pub type BlockId = u8;
pub const AIR: BlockId = 0;
pub const GRASS: BlockId = 1;
pub const DIRT: BlockId = 2;
pub const STONE: BlockId = 3;
pub const SAND: BlockId = 4;
pub const SNOW: BlockId = 5;
pub const MOSS: BlockId = 6;
pub const GRAVEL: BlockId = 7;
pub const GLOWSTONE: BlockId = 8;
pub const WOOD: BlockId = 9;
pub const LEAVES: BlockId = 10;
pub const RED_FLOWER: BlockId = 11;
pub const YELLOW_FLOWER: BlockId = 12;
pub const BLUE_FLOWER: BlockId = 13;
pub const FERN: BlockId = 14;
pub const TALL_GRASS: BlockId = 15;
pub const MAX_BUILTIN_BLOCK: BlockId = TALL_GRASS;

#[inline]
pub fn valid_block(block: BlockId) -> bool {
    block <= MAX_BUILTIN_BLOCK || crate::content::block_def(block).is_some()
}

#[inline]
pub fn is_plant(block: BlockId) -> bool {
    crate::content::block_flags(block) & crate::content::PLANT != 0
}

#[inline]
pub fn is_cutout(block: BlockId) -> bool {
    crate::content::block_flags(block) & crate::content::CUTOUT != 0
}

#[inline]
pub fn is_opaque(block: BlockId) -> bool {
    crate::content::block_flags(block) & crate::content::OPAQUE != 0
}

#[inline]
pub fn is_solid(block: BlockId) -> bool {
    crate::content::block_flags(block) & crate::content::SOLID != 0
}

#[inline]
pub fn is_replaceable(block: BlockId) -> bool {
    crate::content::block_flags(block) & crate::content::REPLACEABLE != 0
}

#[inline]
pub fn supports_plant(block: BlockId) -> bool {
    crate::content::block_flags(block) & crate::content::SUPPORTS_PLANT != 0
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct ChunkKey {
    pub x: i32,
    pub y: i32,
    pub z: i32,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Chunk {
    pub key: ChunkKey,
    pub version: u64,
    pub blocks: Vec<BlockId>,
}

impl Chunk {
    /// Local x changes fastest, followed by z, then y.
    pub fn index(local: [usize; 3]) -> Option<usize> {
        let [x, y, z] = local;
        if x < CHUNK_SIZE && y < CHUNK_SIZE && z < CHUNK_SIZE {
            Some(x + CHUNK_SIZE * (z + CHUNK_SIZE * y))
        } else {
            None
        }
    }

    pub fn block(&self, local: [usize; 3]) -> Option<BlockId> {
        Self::index(local).map(|index| self.blocks[index])
    }

    /// Returns the new version; an unchanged value does not advance it.
    pub fn set_block(&mut self, local: [usize; 3], block: BlockId) -> Option<u64> {
        if !valid_block(block) {
            return None;
        }
        let index = Self::index(local)?;
        if self.blocks[index] != block {
            let version = self.version.checked_add(1)?;
            self.blocks[index] = block;
            self.version = version;
        }
        Some(self.version)
    }
}

/// A chunk loaded from storage or generated by a worker, together with the
/// sparse overrides needed to preserve edit history if it enters the cache.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LoadedChunk {
    pub chunk: Chunk,
    edits: BTreeMap<u16, BlockId>,
}

/// A validated block edit staged from the authoritative cached chunk.
///
/// `before_snapshot` and `after_snapshot` are exact BGED v2 file bytes, with an
/// empty vector representing a missing override file. The private fields keep
/// the prepared in-memory state tied to the version and per-chunk edit epoch
/// from which it was computed.
#[derive(Clone, Debug)]
pub struct PreparedEdit {
    pub key: ChunkKey,
    pub expected_version: u64,
    pub new_version: u64,
    pub before_snapshot: Vec<u8>,
    pub after_snapshot: Vec<u8>,
    pub changed: bool,
    expected_edit_epoch: u64,
    expected_revision: u64,
    revision: Arc<AtomicU64>,
    before_edits: BTreeMap<u16, BlockId>,
    after_chunk: Chunk,
    after_edits: BTreeMap<u16, BlockId>,
}

type LocatedEdit = (i32, i32, i32, [usize; 3], BlockId);

pub fn world_to_chunk(x: i32, y: i32, z: i32) -> (ChunkKey, [usize; 3]) {
    let size = CHUNK_SIZE as i32;
    (
        ChunkKey {
            x: x.div_euclid(size),
            y: y.div_euclid(size),
            z: z.div_euclid(size),
        },
        [
            x.rem_euclid(size) as usize,
            y.rem_euclid(size) as usize,
            z.rem_euclid(size) as usize,
        ],
    )
}

pub fn generate_chunk(key: ChunkKey, seed: u64) -> Chunk {
    let mut blocks = vec![AIR; CHUNK_VOLUME];
    let bottom = i64::from(key.y) * CHUNK_SIZE as i64;
    if bottom + CHUNK_SIZE as i64 <= i64::from(BEDROCK_Y) {
        blocks.fill(STONE);
        return Chunk {
            key,
            version: 0,
            blocks,
        };
    }
    if bottom > i64::from(MAX_GENERATED_HEIGHT) {
        return Chunk {
            key,
            version: 0,
            blocks,
        };
    }
    let mut patterns = HashMap::new();
    for z in 0..CHUNK_SIZE {
        for x in 0..CHUNK_SIZE {
            let world_x = i64::from(key.x) * CHUNK_SIZE as i64 + x as i64;
            let world_z = i64::from(key.z) * CHUNK_SIZE as i64 + z as i64;
            let column = terrain_column(world_x, world_z, seed);
            let pattern =
                if bottom <= column.height && bottom + CHUNK_SIZE as i64 > column.height - 4 {
                    surface_pattern(world_x, world_z, seed, &mut patterns)
                } else {
                    0
                };
            for y in 0..CHUNK_SIZE {
                let world_y = bottom + y as i64;
                let block =
                    generated_block_with_pattern(world_x, world_y, world_z, column, pattern, seed);
                blocks[Chunk::index([x, y, z]).unwrap()] = block;
            }
        }
    }
    decorate_chunk(key, seed, &mut blocks, &mut patterns);
    Chunk {
        key,
        version: 0,
        blocks,
    }
}

fn generated_block(x: i64, y: i64, z: i64, seed: u64) -> BlockId {
    let column = terrain_column(x, z, seed);
    let ground = generated_block_in_column(x, y, z, column, seed);
    if ground != AIR {
        return ground;
    }
    if let Some(tree) = tree_block_at(x, y, z, seed) {
        return tree;
    }
    if y == column.height + 1 {
        let soil = generated_block_in_column(x, column.height, z, column, seed);
        return ground_plant(x, z, seed, column.biome, soil);
    }
    AIR
}

const TREE_CELL: i64 = 16;
const TREE_RADIUS: i64 = 3;

#[derive(Clone, Copy)]
struct Tree {
    x: i64,
    z: i64,
    ground_y: i64,
    trunk_top: i64,
}

fn tree_anchor(cell_x: i64, cell_z: i64, seed: u64) -> Option<Tree> {
    let hash = lattice_hash(seed ^ 0x906f_89ad, cell_x, 0, cell_z);
    let x = cell_x * TREE_CELL + 2 + ((hash >> 8) % 13) as i64;
    let z = cell_z * TREE_CELL + 2 + ((hash >> 16) % 13) as i64;
    if x.abs() <= 14 && z.abs() <= 14 {
        return None;
    }
    let column = terrain_column(x, z, seed);
    let frequency = match column.biome {
        Biome::Forest => 380,
        Biome::Plains => 45,
        _ => 0,
    };
    if hash % 1000 >= frequency
        || !supports_plant(generated_block_in_column(x, column.height, z, column, seed))
    {
        return None;
    }
    Some(Tree {
        x,
        z,
        ground_y: column.height,
        trunk_top: column.height + 5 + ((hash >> 28) % 3) as i64,
    })
}

fn tree_piece(tree: Tree, x: i64, y: i64, z: i64) -> Option<BlockId> {
    let dx = (x - tree.x).abs();
    let dz = (z - tree.z).abs();
    if dx == 0 && dz == 0 && y > tree.ground_y && y <= tree.trunk_top {
        return Some(WOOD);
    }
    let layer = (y - tree.trunk_top).abs();
    let radius = match layer {
        0 => 3,
        1 => 2,
        2 => 1,
        _ => return None,
    };
    (dx <= radius && dz <= radius && dx + dz <= radius + 1).then_some(LEAVES)
}

fn tree_block_at(x: i64, y: i64, z: i64, seed: u64) -> Option<BlockId> {
    let mut leaf = false;
    for cz in (z - TREE_RADIUS).div_euclid(TREE_CELL)..=(z + TREE_RADIUS).div_euclid(TREE_CELL) {
        for cx in (x - TREE_RADIUS).div_euclid(TREE_CELL)..=(x + TREE_RADIUS).div_euclid(TREE_CELL)
        {
            if let Some(tree) = tree_anchor(cx, cz, seed) {
                match tree_piece(tree, x, y, z) {
                    Some(WOOD) => return Some(WOOD),
                    Some(LEAVES) => leaf = true,
                    _ => {}
                }
            }
        }
    }
    leaf.then_some(LEAVES)
}

fn ground_plant(x: i64, z: i64, seed: u64, biome: Biome, soil: BlockId) -> BlockId {
    if !supports_plant(soil) || (x.abs() <= 12 && z.abs() <= 12) {
        return AIR;
    }
    let cluster = noise2(x, z, 19, seed ^ 0x36f9_91cb);
    let hash = lattice_hash(seed ^ 0xc483_f4a2, x, 0, z);
    let roll = hash % 1000;
    match biome {
        Biome::Forest if cluster > -0.3 => match roll {
            0..=129 => FERN,
            130..=199 => TALL_GRASS,
            200..=214 => BLUE_FLOWER,
            _ => AIR,
        },
        Biome::Plains if cluster > -0.15 => match roll {
            0..=199 => TALL_GRASS,
            200..=224 => RED_FLOWER,
            225..=249 => YELLOW_FLOWER,
            250..=269 => BLUE_FLOWER,
            _ => AIR,
        },
        _ => AIR,
    }
}

fn decorate_chunk(
    key: ChunkKey,
    seed: u64,
    blocks: &mut [BlockId],
    patterns: &mut HashMap<(i64, i64), [u8; 64]>,
) {
    let first_x = i64::from(key.x) * CHUNK_SIZE as i64;
    let first_y = i64::from(key.y) * CHUNK_SIZE as i64;
    let first_z = i64::from(key.z) * CHUNK_SIZE as i64;
    let last_x = first_x + CHUNK_SIZE as i64 - 1;
    let last_z = first_z + CHUNK_SIZE as i64 - 1;
    for cz in
        (first_z - TREE_RADIUS).div_euclid(TREE_CELL)..=(last_z + TREE_RADIUS).div_euclid(TREE_CELL)
    {
        for cx in (first_x - TREE_RADIUS).div_euclid(TREE_CELL)
            ..=(last_x + TREE_RADIUS).div_euclid(TREE_CELL)
        {
            let Some(tree) = tree_anchor(cx, cz, seed) else {
                continue;
            };
            for z in (tree.z - TREE_RADIUS).max(first_z)..=(tree.z + TREE_RADIUS).min(last_z) {
                for x in (tree.x - TREE_RADIUS).max(first_x)..=(tree.x + TREE_RADIUS).min(last_x) {
                    for y in (tree.ground_y + 1).max(first_y)
                        ..=(tree.trunk_top + 2).min(first_y + CHUNK_SIZE as i64 - 1)
                    {
                        if let Some(piece) = tree_piece(tree, x, y, z) {
                            let local = [
                                (x - first_x) as usize,
                                (y - first_y) as usize,
                                (z - first_z) as usize,
                            ];
                            let at = Chunk::index(local).unwrap();
                            if blocks[at] == AIR || (piece == WOOD && blocks[at] == LEAVES) {
                                blocks[at] = piece;
                            }
                        }
                    }
                }
            }
        }
    }
    for z in 0..CHUNK_SIZE {
        for x in 0..CHUNK_SIZE {
            let world_x = first_x + x as i64;
            let world_z = first_z + z as i64;
            let column = terrain_column(world_x, world_z, seed);
            let world_y = column.height + 1;
            if !(first_y..first_y + CHUNK_SIZE as i64).contains(&world_y) {
                continue;
            }
            let at = Chunk::index([x, (world_y - first_y) as usize, z]).unwrap();
            if blocks[at] == AIR {
                let pattern = surface_pattern(world_x, world_z, seed, patterns);
                let soil = generated_block_with_pattern(
                    world_x,
                    column.height,
                    world_z,
                    column,
                    pattern,
                    seed,
                );
                blocks[at] = ground_plant(world_x, world_z, seed, column.biome, soil);
            }
        }
    }
}

fn lattice_hash(seed: u64, x: i64, y: i64, z: i64) -> u64 {
    mix(seed
        ^ (x as u64).wrapping_mul(0x9e37_79b9_7f4a_7c15)
        ^ (y as u64).wrapping_mul(0xbf58_476d_1ce4_e5b9)
        ^ (z as u64).wrapping_mul(0x94d0_49bb_1331_11eb))
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Biome {
    Plains,
    Forest,
    Desert,
    Tundra,
    Highland,
}

#[derive(Clone, Copy)]
struct Column {
    height: i64,
    rocky: bool,
    biome: Biome,
}

fn terrain_column(x: i64, z: i64, seed: u64) -> Column {
    let continent = noise2(x, z, 256, seed ^ 0x42ab_51a4);
    let temperature = noise2(x, z, 384, seed ^ 0x8179_e6f2);
    let moisture = noise2(x, z, 320, seed ^ 0x6a03_d2e1);
    let uplift = noise2(x, z, 512, seed ^ 0x9b57_2a13);
    let hills = noise2(x, z, 64, seed ^ 0xd88a_4f9b);
    let detail = noise2(x, z, 24, seed ^ 0x7c14_1583);
    let ridge = 1.0 - noise2(x, z, 96, seed ^ 0xe7d2_391f).abs();
    let mountain = smooth(((uplift - 0.05) / 0.72).clamp(0.0, 1.0));
    let aridity =
        ((temperature + 0.05) * 1.5).clamp(0.0, 1.0) * ((-moisture + 0.05) * 1.5).clamp(0.0, 1.0);
    let forested = (moisture * 1.5).clamp(0.0, 1.0);
    let polar = ((-temperature - 0.1) * 1.6).clamp(0.0, 1.0);
    let dunes = noise2(x + z / 3, z, 42, seed ^ 0xb62d_7a35) * 3.4
        + noise2(x, z, 14, seed ^ 0x7b43_719a) * 0.8;
    let height = (21.0
        + continent * 6.0
        + hills * (3.5 + mountain * 3.0)
        + detail * (1.5 - polar * 0.8)
        + aridity * dunes
        + forested * noise2(x, z, 48, seed ^ 0x2740_83be) * 2.0
        + mountain * mountain * ridge * ridge * 24.0)
        .round() as i64;
    let biome = if mountain > 0.72 && height > 34 {
        Biome::Highland
    } else if temperature < -0.23 {
        Biome::Tundra
    } else if temperature > 0.12 && moisture < -0.12 {
        Biome::Desert
    } else if moisture > 0.08 {
        Biome::Forest
    } else {
        Biome::Plains
    };
    Column {
        height,
        rocky: biome == Biome::Highland && height > 41,
        biome,
    }
}

pub(crate) fn terrain_height(x: i64, z: i64, seed: u64) -> i64 {
    terrain_column(x, z, seed).height
}

fn generated_block_in_column(x: i64, y: i64, z: i64, column: Column, seed: u64) -> BlockId {
    let pattern = if y >= column.height - 4 && y <= column.height {
        surface_pattern(x, z, seed, &mut HashMap::new())
    } else {
        0
    };
    generated_block_with_pattern(x, y, z, column, pattern, seed)
}

fn generated_block_with_pattern(
    x: i64,
    y: i64,
    z: i64,
    column: Column,
    pattern: u8,
    seed: u64,
) -> BlockId {
    if y <= i64::from(BEDROCK_Y) {
        return STONE;
    }
    if y > column.height {
        AIR
    } else {
        // Coarse caverns and finer breaks share absolute world coordinates, so
        // both horizontal and vertical chunk faces sample the same field.
        if y >= i64::from(BEDROCK_Y) + 5 {
            let caverns = noise3(x, y, z, 22, seed ^ 0x9907_ae41);
            let breaks = noise3(x, y, z, 9, seed ^ 0x287a_13dc);
            let near_spawn = x.abs() <= 12 && z.abs() <= 12;
            let threshold = if y >= column.height - 5 { 0.66 } else { 0.35 };
            if !(near_spawn && y >= column.height - 7) && caverns + breaks * 0.4 > threshold {
                return AIR;
            }
        }
        if y < column.height - 4 {
            return STONE;
        }
        let top = match column.biome {
            Biome::Plains => [GRASS, GRASS, GRAVEL, STONE][pattern as usize],
            Biome::Forest => [GRASS, MOSS, MOSS, STONE][pattern as usize],
            Biome::Desert => [SAND, SAND, GRAVEL, STONE][pattern as usize],
            Biome::Tundra => [SNOW, SNOW, GRAVEL, STONE][pattern as usize],
            Biome::Highland => [STONE, GRAVEL, GRAVEL, SNOW][pattern as usize],
        };
        if y == column.height {
            return top;
        }
        match column.biome {
            Biome::Desert if y >= column.height - 3 => SAND,
            Biome::Tundra if y >= column.height - 2 => DIRT,
            Biome::Highland if column.rocky || y < column.height - 2 => STONE,
            _ if y >= column.height - 3 => DIRT,
            _ => STONE,
        }
    }
}

/// Collapse a small Wang-like ground-cover field. Border cells are the common
/// substrate, so independently generated regions always meet legally. The
/// solver propagates neighbor constraints after each minimum-entropy choice;
/// it is only evaluated once per region while building a chunk.
fn surface_pattern(x: i64, z: i64, seed: u64, cache: &mut HashMap<(i64, i64), [u8; 64]>) -> u8 {
    const CELL_SIZE: i64 = 4;
    const REGION_SIZE: i64 = 8 * CELL_SIZE;
    let region = (x.div_euclid(REGION_SIZE), z.div_euclid(REGION_SIZE));
    let tiles = cache
        .entry(region)
        .or_insert_with(|| collapse_surface(region, seed));
    let cx = x.rem_euclid(REGION_SIZE) / CELL_SIZE;
    let cz = z.rem_euclid(REGION_SIZE) / CELL_SIZE;
    let tile = tiles[(cx + cz * 8) as usize];
    if tile == 0 {
        return 0;
    }
    let edge = noise2(x, z, 7, seed ^ 0x56d8_2f4a) + noise2(x, z, 3, seed ^ 0x83a2_1c59) * 0.35;
    match tile {
        1 if edge > 0.37 => 2,
        2 if edge < -0.28 => 1,
        3 if edge < -0.32 => 2,
        _ => tile,
    }
}

const SURFACE_NEIGHBORS: [u8; 4] = [0b0011, 0b0111, 0b1110, 0b1100];

fn collapse_surface(region: (i64, i64), seed: u64) -> [u8; 64] {
    let mut possible = [0b1111u8; 64];
    for z in 0..8 {
        for x in 0..8 {
            if x == 0 || x == 7 || z == 0 || z == 7 {
                possible[x + z * 8] = 1;
            }
        }
    }
    let region_seed = mix(seed
        ^ (region.0 as u64).wrapping_mul(0x9e37_79b9_7f4a_7c15)
        ^ (region.1 as u64).wrapping_mul(0xbf58_476d_1ce4_e5b9));
    for step in 0..64u64 {
        // Arc-consistency propagation: each candidate must have support in
        // every neighboring cell. This prevents isolated patch/dense tiles.
        loop {
            let mut changed = false;
            for z in 0..8 {
                for x in 0..8 {
                    let index = x + z * 8;
                    let mut mask = possible[index];
                    for neighbor in [
                        (x > 0).then_some(index.wrapping_sub(1)),
                        (x < 7).then_some(index + 1),
                        (z > 0).then_some(index.wrapping_sub(8)),
                        (z < 7).then_some(index + 8),
                    ]
                    .into_iter()
                    .flatten()
                    {
                        let mut supported = 0;
                        for (tile, allowed) in SURFACE_NEIGHBORS.iter().enumerate() {
                            if possible[neighbor] & allowed != 0 {
                                supported |= 1 << tile;
                            }
                        }
                        mask &= supported;
                    }
                    if mask == 0 {
                        return [0; 64];
                    }
                    if mask != possible[index] {
                        possible[index] = mask;
                        changed = true;
                    }
                }
            }
            if !changed {
                break;
            }
        }
        let next = possible
            .iter()
            .enumerate()
            .filter(|(_, mask)| mask.count_ones() > 1)
            .min_by_key(|(index, mask)| {
                (mask.count_ones(), mix(region_seed ^ step ^ *index as u64))
            });
        let Some((index, mask)) = next else {
            break;
        };
        let weights = [1u32, 4, 8, 3];
        let total: u32 = weights
            .iter()
            .enumerate()
            .filter(|(tile, _)| mask & (1 << tile) != 0)
            .map(|(_, weight)| weight)
            .sum();
        let mut choice =
            (mix(region_seed ^ step.wrapping_mul(0x94d0_49bb_1331_11eb)) % u64::from(total)) as u32;
        for (tile, weight) in weights.into_iter().enumerate() {
            if mask & (1 << tile) == 0 {
                continue;
            }
            if choice < weight {
                possible[index] = 1 << tile;
                break;
            }
            choice -= weight;
        }
    }
    std::array::from_fn(|index| possible[index].trailing_zeros() as u8)
}

fn noise2(x: i64, z: i64, scale: i64, seed: u64) -> f64 {
    let x0 = x.div_euclid(scale);
    let z0 = z.div_euclid(scale);
    let tx = smooth(x.rem_euclid(scale) as f64 / scale as f64);
    let tz = smooth(z.rem_euclid(scale) as f64 / scale as f64);
    let a = lerp(lattice(seed, x0, 0, z0), lattice(seed, x0 + 1, 0, z0), tx);
    let b = lerp(
        lattice(seed, x0, 0, z0 + 1),
        lattice(seed, x0 + 1, 0, z0 + 1),
        tx,
    );
    lerp(a, b, tz)
}

fn noise3(x: i64, y: i64, z: i64, scale: i64, seed: u64) -> f64 {
    let x0 = x.div_euclid(scale);
    let y0 = y.div_euclid(scale);
    let z0 = z.div_euclid(scale);
    let tx = smooth(x.rem_euclid(scale) as f64 / scale as f64);
    let ty = smooth(y.rem_euclid(scale) as f64 / scale as f64);
    let tz = smooth(z.rem_euclid(scale) as f64 / scale as f64);
    let layer = |z_lattice| {
        let a = lerp(
            lattice(seed, x0, y0, z_lattice),
            lattice(seed, x0 + 1, y0, z_lattice),
            tx,
        );
        let b = lerp(
            lattice(seed, x0, y0 + 1, z_lattice),
            lattice(seed, x0 + 1, y0 + 1, z_lattice),
            tx,
        );
        lerp(a, b, ty)
    };
    lerp(layer(z0), layer(z0 + 1), tz)
}

fn lattice(seed: u64, x: i64, y: i64, z: i64) -> f64 {
    let hash = lattice_hash(seed, x, y, z);
    ((hash >> 40) as f64 / 8_388_607.5) - 1.0
}

fn smooth(t: f64) -> f64 {
    t * t * (3.0 - 2.0 * t)
}

fn lerp(a: f64, b: f64, t: f64) -> f64 {
    a + (b - a) * t
}

fn mix(mut value: u64) -> u64 {
    value = (value ^ (value >> 30)).wrapping_mul(0xbf58476d1ce4e5b9);
    value = (value ^ (value >> 27)).wrapping_mul(0x94d049bb133111eb);
    value ^ (value >> 31)
}

struct CacheEntry {
    chunk: Chunk,
    edits: BTreeMap<u16, BlockId>,
    last_used: u64,
}

pub struct World {
    seed: u64,
    storage: Storage,
    cache: HashMap<ChunkKey, CacheEntry>,
    /// Per-key epochs exist only while asynchronous loads for that key are in flight.
    edit_epochs: HashMap<ChunkKey, u64>,
    in_flight_by_key: HashMap<ChunkKey, usize>,
    in_flight_loads: HashMap<(ChunkKey, u64), usize>,
    pending_snapshots: HashMap<ChunkKey, Option<Vec<u8>>>,
    prepared_revisions: HashMap<ChunkKey, Weak<AtomicU64>>,
    max_cached_chunks: usize,
    clock: u64,
}

impl World {
    pub fn new(seed: u64, path: PathBuf) -> io::Result<Self> {
        Self::with_capacity(seed, path, 512)
    }

    pub fn with_capacity(seed: u64, path: PathBuf, max_cached_chunks: usize) -> io::Result<Self> {
        if max_cached_chunks == 0 {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                "cache capacity must be positive",
            ));
        }
        Ok(Self {
            seed,
            storage: Storage::new(path, seed)?,
            cache: HashMap::new(),
            edit_epochs: HashMap::new(),
            in_flight_by_key: HashMap::new(),
            in_flight_loads: HashMap::new(),
            pending_snapshots: HashMap::new(),
            prepared_revisions: HashMap::new(),
            max_cached_chunks,
            clock: 0,
        })
    }

    /// Returns an owned, stable snapshot suitable for sending or meshing.
    pub fn get_chunk(&mut self, key: ChunkKey) -> io::Result<Chunk> {
        self.ensure_loaded(key)?;
        Ok(self.cache[&key].chunk.clone())
    }

    /// Returns an owned snapshot only when this world already has the chunk in
    /// its authoritative cache. This method never loads or generates terrain.
    pub fn cached_chunk(&mut self, key: ChunkKey) -> Option<Chunk> {
        self.clock = self.clock.wrapping_add(1);
        let entry = self.cache.get_mut(&key)?;
        entry.last_used = self.clock;
        Some(entry.chunk.clone())
    }

    /// Loads and generates without consulting or mutating this world's cache.
    /// Intended for the loader workers, which keep independent `World` values.
    pub fn load_chunk_uncached(&self, key: ChunkKey) -> io::Result<LoadedChunk> {
        let saved = self.storage.load(key)?;
        Ok(Self::assemble_loaded_chunk(key, self.seed, saved))
    }

    /// A cloneable storage handle for persistence workers. The caller should
    /// keep its file operations off the simulation tick.
    pub fn storage_handle(&self) -> Storage {
        self.storage.clone()
    }

    /// The current per-key load epoch. Epoch entries are retained only while
    /// loads are in flight, so exploration does not grow a permanent map.
    pub fn edit_epoch(&self, key: ChunkKey) -> u64 {
        self.edit_epochs.get(&key).copied().unwrap_or(0)
    }

    /// Registers an asynchronous load and returns its per-key epoch plus any
    /// newer journal snapshot that has not reached the BGED file yet.
    pub fn begin_chunk_load(&mut self, key: ChunkKey) -> io::Result<(u64, Option<Vec<u8>>)> {
        let epoch = self.edit_epoch(key);
        let count = self
            .in_flight_loads
            .get(&(key, epoch))
            .copied()
            .unwrap_or(0);
        let key_count = self.in_flight_by_key.get(&key).copied().unwrap_or(0);
        let next_count = count
            .checked_add(1)
            .ok_or_else(|| io::Error::other("chunk load count exhausted"))?;
        let next_key_count = key_count
            .checked_add(1)
            .ok_or_else(|| io::Error::other("chunk load count exhausted"))?;
        self.in_flight_loads.insert((key, epoch), next_count);
        self.in_flight_by_key.insert(key, next_key_count);
        let pending = self
            .pending_snapshots
            .get(&key)
            .map(|snapshot| snapshot.clone().unwrap_or_default());
        Ok((epoch, pending))
    }

    /// Retires a registered request after its result is installed, rejected,
    /// or fails. This bounds epoch bookkeeping by outstanding load work.
    pub fn finish_chunk_load(&mut self, key: ChunkKey, epoch: u64) {
        let retired = if let Some(count) = self.in_flight_loads.get_mut(&(key, epoch)) {
            *count -= 1;
            if *count == 0 {
                self.in_flight_loads.remove(&(key, epoch));
            }
            true
        } else {
            false
        };
        if !retired {
            return;
        }
        if let Some(count) = self.in_flight_by_key.get_mut(&key) {
            *count -= 1;
            if *count == 0 {
                self.in_flight_by_key.remove(&key);
                self.edit_epochs.remove(&key);
            }
        }
    }

    /// Builds a loaded chunk from a captured BGED snapshot without file I/O.
    /// An empty snapshot is the generated baseline.
    pub fn load_chunk_snapshot_uncached(
        &self,
        key: ChunkKey,
        snapshot: &[u8],
    ) -> io::Result<LoadedChunk> {
        let saved = self
            .storage
            .decode_snapshot((!snapshot.is_empty()).then_some(snapshot))?;
        Ok(Self::assemble_loaded_chunk(key, self.seed, saved))
    }

    /// Installs a worker result only when this key is still absent and has not
    /// been edited since the request captured `expected_edit_epoch`.
    pub fn install_loaded_if_absent(
        &mut self,
        loaded: LoadedChunk,
        expected_edit_epoch: u64,
    ) -> io::Result<bool> {
        let key = loaded.chunk.key;
        if loaded.chunk.blocks.len() != CHUNK_VOLUME
            || loaded.chunk.blocks.iter().any(|&block| !valid_block(block))
            || loaded
                .edits
                .iter()
                .any(|(&index, &block)| index as usize >= CHUNK_VOLUME || !valid_block(block))
        {
            self.finish_chunk_load(key, expected_edit_epoch);
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                "invalid loaded chunk result",
            ));
        }
        let installed =
            !self.cache.contains_key(&key) && self.edit_epoch(key) == expected_edit_epoch;
        if installed {
            self.cache_loaded_chunk(loaded);
        }
        self.finish_chunk_load(key, expected_edit_epoch);
        Ok(installed)
    }

    /// Reads the exact persisted override snapshot for journal comparisons.
    pub fn read_chunk_snapshot(&self, key: ChunkKey) -> io::Result<Option<Vec<u8>>> {
        if let Some(snapshot) = self.pending_snapshots.get(&key) {
            return Ok(snapshot.clone());
        }
        self.storage.read_snapshot(key)
    }

    /// Clears a journal-backed snapshot marker after a storage worker has
    /// atomically checkpointed the matching BGED bytes. Does no disk I/O.
    pub fn clear_checkpointed_snapshot(&mut self, key: ChunkKey, snapshot: &[u8]) -> bool {
        if self
            .pending_snapshots
            .get(&key)
            .is_some_and(|pending| pending.as_deref().unwrap_or_default() == snapshot)
        {
            self.pending_snapshots.remove(&key);
            true
        } else {
            false
        }
    }

    /// Validates and restores one committed BGED snapshot during journal replay.
    /// The write is atomic, and a cached copy is refreshed if it exists.
    pub fn restore_snapshot(&mut self, key: ChunkKey, snapshot: &[u8]) -> io::Result<()> {
        let value = (!snapshot.is_empty()).then_some(snapshot);
        let existing = self.storage.read_snapshot(key)?;
        self.storage.decode_snapshot(existing.as_deref())?;
        let saved = self.storage.decode_snapshot(value)?;
        let loaded = Self::assemble_loaded_chunk(key, self.seed, saved);
        self.bump_edit_epoch(key)?;
        self.advance_prepared_revision(key)?;
        if let Err(error) = self.storage.replace_snapshot(key, value) {
            self.cache.remove(&key);
            return Err(error);
        }
        self.pending_snapshots.remove(&key);
        if let Some(entry) = self.cache.get_mut(&key) {
            entry.chunk = loaded.chunk;
            entry.edits = loaded.edits;
        }
        Ok(())
    }

    pub fn get_block(&mut self, x: i32, y: i32, z: i32) -> io::Result<BlockId> {
        let (key, local) = world_to_chunk(x, y, z);
        self.ensure_loaded(key)?;
        Ok(self.cache[&key].chunk.block(local).unwrap())
    }

    /// A successful return means the changed block and version have been saved.
    pub fn edit(&mut self, x: i32, y: i32, z: i32, block: BlockId) -> io::Result<(ChunkKey, u64)> {
        let (key, _) = world_to_chunk(x, y, z);
        self.ensure_loaded(key)?;
        let prepared = self.prepare_edit(x, y, z, block)?;
        if !prepared.changed {
            return Ok((prepared.key, prepared.new_version));
        }
        if self.in_flight_by_key.contains_key(&key) && self.edit_epoch(key) == u64::MAX {
            return Err(io::Error::other("chunk load epoch exhausted"));
        }
        if prepared.revision.load(Ordering::Acquire) == u64::MAX {
            return Err(io::Error::other("prepared edit revision exhausted"));
        }
        let saved = self.storage.decode_snapshot(
            (!prepared.after_snapshot.is_empty()).then_some(prepared.after_snapshot.as_slice()),
        )?;
        if let Err(error) = self.storage.save(key, &saved) {
            // The rename may have succeeded before a directory-sync error.
            // Invalidate requests and reload from disk on next access.
            self.bump_edit_epoch(key)?;
            self.advance_prepared_revision(key)?;
            self.cache.remove(&key);
            return Err(error);
        }
        self.apply_prepared_edit_inner(prepared, false)
    }

    /// Prepares an edit from the authoritative cache only. Missing chunks are
    /// reported as WouldBlock so server tick code can wait for a loader result.
    pub fn prepare_edit(
        &mut self,
        x: i32,
        y: i32,
        z: i32,
        block: BlockId,
    ) -> io::Result<PreparedEdit> {
        let edits = self.prepare_edits(&[(x, y, z, block)])?;
        Ok(edits
            .into_iter()
            .next()
            .expect("one input targets one chunk"))
    }

    /// Prepares a multi-block edit as one versioned snapshot per touched chunk.
    /// Every target must already be in the authoritative cache.
    pub fn prepare_edits(
        &mut self,
        edits: &[(i32, i32, i32, BlockId)],
    ) -> io::Result<Vec<PreparedEdit>> {
        let mut grouped: HashMap<ChunkKey, Vec<LocatedEdit>> = HashMap::new();
        let mut coordinates = HashSet::with_capacity(edits.len());
        for &(x, y, z, block) in edits {
            if !valid_block(block) {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidInput,
                    "unknown block identifier",
                ));
            }
            if y <= BEDROCK_Y {
                return Err(io::Error::new(
                    io::ErrorKind::PermissionDenied,
                    "world bottom is immutable",
                ));
            }
            if !coordinates.insert((x, y, z)) {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidInput,
                    "duplicate coordinate in prepared edits",
                ));
            }
            let (key, local) = world_to_chunk(x, y, z);
            grouped
                .entry(key)
                .or_default()
                .push((x, y, z, local, block));
        }

        let mut keys: Vec<_> = grouped.keys().copied().collect();
        keys.sort_by_key(|key| (key.x, key.y, key.z));
        let mut prepared = Vec::with_capacity(keys.len());
        for key in keys {
            let entry = self.cache.get(&key).ok_or_else(|| {
                io::Error::new(
                    io::ErrorKind::WouldBlock,
                    "chunk is not in the authoritative cache",
                )
            })?;
            let before_edits = entry.edits.clone();
            let mut after_edits = before_edits.clone();
            let mut after_chunk = entry.chunk.clone();
            after_chunk.version = 0;
            let mut changed = false;
            for &(x, y, z, local, block) in &grouped[&key] {
                let index = Chunk::index(local).expect("world_to_chunk returns local coordinates");
                if after_chunk.blocks[index] == block {
                    continue;
                }
                changed = true;
                after_chunk
                    .set_block(local, block)
                    .expect("prepared edits were validated and have a bounded block count");
                let baseline = generated_block(i64::from(x), i64::from(y), i64::from(z), self.seed);
                if block == baseline {
                    after_edits.remove(&(index as u16));
                } else {
                    after_edits.insert(index as u16, block);
                }
            }
            let new_version = if changed {
                entry
                    .chunk
                    .version
                    .checked_add(1)
                    .ok_or_else(|| io::Error::other("chunk version exhausted"))?
            } else {
                entry.chunk.version
            };
            after_chunk.version = new_version;
            let before_snapshot = self
                .storage
                .encode_snapshot(&SavedEdits {
                    version: entry.chunk.version,
                    blocks: before_edits.clone(),
                })?
                .unwrap_or_default();
            let after_snapshot = self
                .storage
                .encode_snapshot(&SavedEdits {
                    version: new_version,
                    blocks: after_edits.clone(),
                })?
                .unwrap_or_default();

            let expected_version = entry.chunk.version;
            let expected_edit_epoch = self.edit_epoch(key);
            let (revision, expected_revision) = self.prepared_revision(key);
            prepared.push(PreparedEdit {
                key,
                expected_version,
                new_version,
                before_snapshot,
                after_snapshot,
                changed,
                expected_edit_epoch,
                expected_revision,
                revision,
                before_edits,
                after_chunk,
                after_edits,
            });
        }
        Ok(prepared)
    }

    /// Applies a WAL-synced edit to memory without writing the BGED snapshot.
    /// The pending snapshot remains authoritative across cache eviction until a
    /// successful checkpoint clears it.
    pub fn apply_prepared_edit(&mut self, prepared: PreparedEdit) -> io::Result<(ChunkKey, u64)> {
        let mut applied = self.apply_prepared_edits(vec![prepared])?;
        Ok(applied.pop().expect("single prepared edit"))
    }

    /// Atomically validates and applies one prepared snapshot per chunk in
    /// memory. It performs no disk I/O and records overlays until checkpointed.
    pub fn apply_prepared_edits(
        &mut self,
        prepared: Vec<PreparedEdit>,
    ) -> io::Result<Vec<(ChunkKey, u64)>> {
        let mut keys = HashSet::with_capacity(prepared.len());
        for edit in &prepared {
            if !keys.insert(edit.key) {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidInput,
                    "duplicate chunk in prepared edits",
                ));
            }
            self.validate_prepared_edit(edit)?;
            if edit.changed
                && self.in_flight_by_key.contains_key(&edit.key)
                && self.edit_epoch(edit.key) == u64::MAX
            {
                return Err(io::Error::other("chunk load epoch exhausted"));
            }
            if edit.changed && edit.revision.load(Ordering::Acquire) == u64::MAX {
                return Err(io::Error::other("prepared edit revision exhausted"));
            }
        }

        let mut versions = Vec::with_capacity(prepared.len());
        for edit in prepared {
            versions.push((edit.key, edit.new_version));
            self.apply_prepared_edit_inner(edit, true)?;
        }
        Ok(versions)
    }

    fn apply_prepared_edit_inner(
        &mut self,
        prepared: PreparedEdit,
        keep_pending_snapshot: bool,
    ) -> io::Result<(ChunkKey, u64)> {
        let key = prepared.key;
        self.validate_prepared_edit(&prepared)?;
        if !prepared.changed {
            return Ok((key, prepared.new_version));
        }

        self.bump_edit_epoch(key)?;
        self.advance_prepared_revision(key)?;
        if keep_pending_snapshot {
            self.pending_snapshots.insert(
                key,
                (!prepared.after_snapshot.is_empty()).then_some(prepared.after_snapshot.clone()),
            );
        } else {
            self.pending_snapshots.remove(&key);
        }
        self.cache_loaded_chunk(LoadedChunk {
            chunk: prepared.after_chunk,
            edits: prepared.after_edits,
        });
        Ok((key, prepared.new_version))
    }

    fn validate_prepared_edit(&self, prepared: &PreparedEdit) -> io::Result<()> {
        if prepared.revision.load(Ordering::Acquire) != prepared.expected_revision {
            return Err(io::Error::new(
                io::ErrorKind::WouldBlock,
                "prepared edit was invalidated by a newer chunk edit",
            ));
        }
        if self.edit_epoch(prepared.key) != prepared.expected_edit_epoch {
            return Err(io::Error::new(
                io::ErrorKind::WouldBlock,
                "prepared edit was invalidated by a newer chunk edit",
            ));
        }
        if let Some(entry) = self.cache.get(&prepared.key)
            && (entry.chunk.version != prepared.expected_version
                || entry.edits != prepared.before_edits)
        {
            return Err(io::Error::new(
                io::ErrorKind::WouldBlock,
                "prepared edit no longer matches the authoritative chunk",
            ));
        }
        Ok(())
    }

    /// Number of journal-backed chunk snapshots waiting for a successful
    /// BGED checkpoint; useful for observable persistence backpressure.
    pub fn pending_snapshot_count(&self) -> usize {
        self.pending_snapshots.len()
    }

    fn prepared_revision(&mut self, key: ChunkKey) -> (Arc<AtomicU64>, u64) {
        self.prepared_revisions
            .retain(|_, revision| revision.strong_count() > 0);
        let revision = self
            .prepared_revisions
            .get(&key)
            .and_then(Weak::upgrade)
            .unwrap_or_else(|| {
                let revision = Arc::new(AtomicU64::new(0));
                self.prepared_revisions
                    .insert(key, Arc::downgrade(&revision));
                revision
            });
        let value = revision.load(Ordering::Acquire);
        (revision, value)
    }

    fn advance_prepared_revision(&mut self, key: ChunkKey) -> io::Result<()> {
        self.prepared_revisions
            .retain(|_, revision| revision.strong_count() > 0);
        let Some(revision) = self.prepared_revisions.get(&key).and_then(Weak::upgrade) else {
            self.prepared_revisions.remove(&key);
            return Ok(());
        };
        revision
            .fetch_update(Ordering::AcqRel, Ordering::Acquire, |value| {
                value.checked_add(1)
            })
            .map(|_| ())
            .map_err(|_| io::Error::other("prepared edit revision exhausted"))
    }

    fn bump_edit_epoch(&mut self, key: ChunkKey) -> io::Result<u64> {
        if !self.in_flight_by_key.contains_key(&key) {
            return Ok(self.edit_epoch(key));
        }
        let next = self
            .edit_epoch(key)
            .checked_add(1)
            .ok_or_else(|| io::Error::other("chunk load epoch exhausted"))?;
        self.edit_epochs.insert(key, next);
        Ok(next)
    }

    fn assemble_loaded_chunk(key: ChunkKey, seed: u64, saved: SavedEdits) -> LoadedChunk {
        let mut chunk = generate_chunk(key, seed);
        for (&index, &block) in &saved.blocks {
            chunk.blocks[index as usize] = block;
        }
        chunk.version = saved.version;
        LoadedChunk {
            chunk,
            edits: saved.blocks,
        }
    }

    fn cache_loaded_chunk(&mut self, loaded: LoadedChunk) {
        self.clock = self.clock.wrapping_add(1);
        if self.cache.len() >= self.max_cached_chunks
            && !self.cache.contains_key(&loaded.chunk.key)
            && let Some((&oldest, _)) = self.cache.iter().min_by_key(|(_, entry)| entry.last_used)
        {
            self.cache.remove(&oldest);
        }
        self.cache.insert(
            loaded.chunk.key,
            CacheEntry {
                chunk: loaded.chunk,
                edits: loaded.edits,
                last_used: self.clock,
            },
        );
    }

    fn ensure_loaded(&mut self, key: ChunkKey) -> io::Result<()> {
        self.clock = self.clock.wrapping_add(1);
        if let Some(entry) = self.cache.get_mut(&key) {
            entry.last_used = self.clock;
            return Ok(());
        }
        let loaded = if let Some(snapshot) = self.pending_snapshots.get(&key) {
            let saved = self.storage.decode_snapshot(snapshot.as_deref())?;
            Self::assemble_loaded_chunk(key, self.seed, saved)
        } else {
            self.load_chunk_uncached(key)?
        };
        self.cache_loaded_chunk(loaded);
        Ok(())
    }
}

#[cfg(test)]
#[path = "world/tests.rs"]
mod tests;
