//! Shared voxel coordinates, deterministic terrain, and authoritative edits.

use std::collections::{BTreeMap, HashMap, HashSet};
use std::io;
use std::path::PathBuf;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Arc, Weak};

use crate::storage::{SavedEdits, Storage};

mod cache;
mod generation;
pub(crate) mod lod;
mod owner_apply;
mod palette;
mod sky;
mod terrain;
use cache::ChunkCache;
pub use generation::generate_chunk;
#[cfg(test)]
pub use generation::generate_chunk_with_contributors;
pub(crate) use generation::{Generator, MAX_GENERATION_IDENTITY_BYTES};
pub(crate) use owner_apply::OwnerApplyReceipt;
pub use palette::{PaletteView, PalettedBlocks};
#[cfg(test)]
pub(crate) use terrain::coast_column_diagnostic;
#[cfg(test)]
use terrain::generated_block;
pub(crate) use terrain::terrain_height;
pub(crate) use terrain::water_feature;
#[cfg(test)]
use terrain::{
    Biome, SURFACE_NEIGHBORS, TREE_RADIUS, collapse_surface, generated_block_in_column,
    ground_plant, terrain_column, tree_anchor,
};

pub const CHUNK_SIZE: usize = 16;
pub const CHUNK_VOLUME: usize = CHUNK_SIZE * CHUNK_SIZE * CHUNK_SIZE;
pub const MAX_TERRAIN_HEIGHT: i32 = 88;
pub const MAX_GENERATED_HEIGHT: i32 = MAX_TERRAIN_HEIGHT + 24;
pub const BEDROCK_Y: i32 = -64;
pub const TERRAIN_GENERATOR_VERSION: u16 = 9;
pub type BlockId = crate::content::BlockStateId;
pub const AIR: BlockId = crate::content::BlockStateId(0);
pub const GRASS: BlockId = crate::content::BlockStateId(1);
pub const DIRT: BlockId = crate::content::BlockStateId(2);
pub const STONE: BlockId = crate::content::BlockStateId(3);
pub const SAND: BlockId = crate::content::BlockStateId(4);
pub const SNOW: BlockId = crate::content::BlockStateId(5);
pub const MOSS: BlockId = crate::content::BlockStateId(6);
pub const GRAVEL: BlockId = crate::content::BlockStateId(7);
pub const GLOWSTONE: BlockId = crate::content::BlockStateId(8);
pub const WOOD: BlockId = crate::content::BlockStateId(9);
pub const LEAVES: BlockId = crate::content::BlockStateId(10);
pub const RED_FLOWER: BlockId = crate::content::BlockStateId(11);
pub const YELLOW_FLOWER: BlockId = crate::content::BlockStateId(12);
pub const BLUE_FLOWER: BlockId = crate::content::BlockStateId(13);
pub const FERN: BlockId = crate::content::BlockStateId(14);
pub const TALL_GRASS: BlockId = crate::content::BlockStateId(15);
pub const WOOD_X: BlockId = crate::content::BlockStateId(256);
pub const WOOD_Z: BlockId = crate::content::BlockStateId(257);
pub const WATER: BlockId = crate::content::BlockStateId(16);
pub const MAX_BUILTIN_BLOCK: BlockId = WATER;

#[inline]
#[cfg(test)]
pub fn is_plant(block: BlockId) -> bool {
    crate::content::block_flags(block) & crate::content::PLANT != 0
}

#[inline]
#[cfg(test)]
pub fn is_cutout(block: BlockId) -> bool {
    crate::content::block_flags(block) & crate::content::CUTOUT != 0
}

#[inline]
#[cfg(test)]
pub fn is_opaque(block: BlockId) -> bool {
    crate::content::block_flags(block) & crate::content::OPAQUE != 0
}

#[inline]
pub fn is_solid(block: BlockId) -> bool {
    crate::content::block_flags(block) & crate::content::SOLID != 0
}

#[inline]
#[cfg(test)]
pub fn is_replaceable(block: BlockId) -> bool {
    crate::content::block_flags(block) & crate::content::REPLACEABLE != 0
}

#[inline]
pub fn supports_plant(block: BlockId) -> bool {
    crate::content::block_flags(block) & crate::content::SUPPORTS_PLANT != 0
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct ChunkKey {
    pub x: i32,
    pub y: i32,
    pub z: i32,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Chunk {
    pub key: ChunkKey,
    pub version: u64,
    pub blocks: PalettedBlocks,
}

impl Chunk {
    pub fn from_blocks(key: ChunkKey, version: u64, blocks: Vec<BlockId>) -> Self {
        Self {
            key,
            version,
            blocks: PalettedBlocks::from(blocks),
        }
    }

    /// Local x changes fastest, followed by z, then y.
    pub fn index(local: [usize; 3]) -> Option<usize> {
        let [x, y, z] = local;
        if x < CHUNK_SIZE && y < CHUNK_SIZE && z < CHUNK_SIZE {
            Some(x + CHUNK_SIZE * (z + CHUNK_SIZE * y))
        } else {
            None
        }
    }

    pub fn block(&self, local: [usize; 3]) -> Option<BlockId> {
        self.blocks.get(Self::index(local)?)
    }

    pub fn block_index(&self, index: usize) -> Option<BlockId> {
        self.blocks.get(index)
    }
}

/// A chunk loaded from storage or generated by a worker, together with the
/// sparse overrides needed to preserve edit history if it enters the cache.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LoadedChunk {
    pub chunk: Chunk,
    edits: BTreeMap<u16, BlockId>,
}

/// A validated block edit staged from the authoritative cached chunk.
///
/// `before_snapshot` and `after_snapshot` are exact BGED v3 file bytes, with an
/// empty vector representing a missing override file. The private fields keep
/// the prepared in-memory state tied to the version and per-chunk edit epoch
/// from which it was computed.
#[derive(Clone, Debug)]
pub struct PreparedEdit {
    pub key: ChunkKey,
    pub expected_version: u64,
    pub new_version: u64,
    pub before_snapshot: Vec<u8>,
    pub after_snapshot: Vec<u8>,
    pub changed: bool,
    expected_revision: u64,
    revision: Arc<AtomicU64>,
    before_chunk: Arc<Chunk>,
    before_edits: BTreeMap<u16, BlockId>,
    after_chunk: Chunk,
    after_edits: BTreeMap<u16, BlockId>,
}

/// A read-only authority stamp invalidated by any committed edit to its chunk.
#[derive(Clone, Debug)]
pub(crate) struct ChunkReadStamp {
    revision: Arc<AtomicU64>,
    expected_revision: u64,
}
impl ChunkReadStamp {
    pub(crate) fn is_current(&self) -> bool {
        self.revision.load(Ordering::Acquire) == self.expected_revision
    }
}

/// Immutable authoritative edit input. A worker may build and encode one
/// chunk's complete sparse after-value without borrowing the live World.
pub(crate) struct EditBasis {
    key: ChunkKey,
    chunk: Arc<Chunk>,
    edits: BTreeMap<u16, BlockId>,
    seed: u64,
    generator: Arc<Generator>,
    storage: Storage,
    catalog: Arc<crate::content::Catalog>,
    revision: Arc<AtomicU64>,
    expected_revision: u64,
}

impl EditBasis {
    pub(crate) fn chunk(&self) -> &Chunk {
        &self.chunk
    }

    pub(crate) fn catalog(&self) -> &crate::content::Catalog {
        &self.catalog
    }

    pub(crate) fn prepare_sparse(&self, edits: &[(u16, BlockId)]) -> io::Result<PreparedEdit> {
        let mut coordinates = HashSet::with_capacity(edits.len());
        let before_edits = self.edits.clone();
        let mut after_edits = before_edits.clone();
        let mut after_chunk = (*self.chunk).clone();
        after_chunk.version = 0;
        let mut changed = false;
        // All contributors, including the builtins, have a chunk-only contract.
        // Reconstruct once, lazily, on the edit worker.
        let mut generated = None;
        for &(cell, block) in edits {
            let index = usize::from(cell);
            if index >= CHUNK_VOLUME
                || !coordinates.insert(cell)
                || self.catalog.state(block).is_none()
            {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidInput,
                    "invalid sparse edit",
                ));
            }
            let local_y = (index / (CHUNK_SIZE * CHUNK_SIZE)) as i64;
            let y = i64::from(self.key.y) * CHUNK_SIZE as i64 + local_y;
            if y <= i64::from(BEDROCK_Y) {
                return Err(io::Error::new(
                    io::ErrorKind::PermissionDenied,
                    "world bottom is immutable",
                ));
            }
            if after_chunk.blocks[index] == block {
                continue;
            }
            changed = true;
            after_chunk.blocks.set(index, block);
            if generated.is_none() {
                generated = Some(
                    self.generator
                        .generate(self.key, self.seed, &self.catalog)?,
                );
            }
            let baseline = generated.as_ref().expect("generated baseline").blocks[index];
            if block == baseline {
                after_edits.remove(&cell);
            } else {
                after_edits.insert(cell, block);
            }
        }
        let new_version = if changed {
            self.chunk
                .version
                .checked_add(1)
                .ok_or_else(|| io::Error::other("chunk version exhausted"))?
        } else {
            self.chunk.version
        };
        after_chunk.version = new_version;
        let before_snapshot = self
            .storage
            .encode_snapshot(&SavedEdits {
                version: self.chunk.version,
                blocks: before_edits.clone(),
            })?
            .unwrap_or_default();
        let after_snapshot = self
            .storage
            .encode_snapshot(&SavedEdits {
                version: new_version,
                blocks: after_edits.clone(),
            })?
            .unwrap_or_default();
        Ok(PreparedEdit {
            key: self.key,
            expected_version: self.chunk.version,
            new_version,
            before_snapshot,
            after_snapshot,
            changed,
            expected_revision: self.expected_revision,
            revision: Arc::clone(&self.revision),
            before_chunk: Arc::clone(&self.chunk),
            before_edits,
            after_chunk,
            after_edits,
        })
    }
}

pub fn world_to_chunk(x: i32, y: i32, z: i32) -> (ChunkKey, [usize; 3]) {
    let size = CHUNK_SIZE as i32;
    (
        ChunkKey {
            x: x.div_euclid(size),
            y: y.div_euclid(size),
            z: z.div_euclid(size),
        },
        [
            x.rem_euclid(size) as usize,
            y.rem_euclid(size) as usize,
            z.rem_euclid(size) as usize,
        ],
    )
}

pub struct World {
    seed: u64,
    storage: Storage,
    catalog: Arc<crate::content::Catalog>,
    generator: Arc<Generator>,
    cache: ChunkCache,
    sky_ceiling: sky::Ceiling,
    /// Per-key epochs exist only while asynchronous loads for that key are in flight.
    edit_epochs: HashMap<ChunkKey, u64>,
    in_flight_by_key: HashMap<ChunkKey, usize>,
    in_flight_loads: HashMap<(ChunkKey, u64), usize>,
    pending_snapshots: HashMap<ChunkKey, Option<Vec<u8>>>,
    prepared_revisions: HashMap<ChunkKey, Weak<AtomicU64>>,
}

impl World {
    #[cfg(test)]
    pub fn new(seed: u64, path: PathBuf) -> io::Result<Self> {
        Self::with_capacity(seed, path, 512)
    }

    pub fn with_capacity(seed: u64, path: PathBuf, max_cached_chunks: usize) -> io::Result<Self> {
        Self::with_capacity_and_catalog(
            seed,
            path,
            max_cached_chunks,
            Arc::new(crate::content::catalog().clone()),
        )
    }

    pub fn with_capacity_and_catalog(
        seed: u64,
        path: PathBuf,
        max_cached_chunks: usize,
        catalog: Arc<crate::content::Catalog>,
    ) -> io::Result<Self> {
        Self::with_generation(seed, path, max_cached_chunks, catalog, Vec::new())
    }

    pub(crate) fn with_generation(
        seed: u64,
        path: PathBuf,
        max_cached_chunks: usize,
        catalog: Arc<crate::content::Catalog>,
        contributors: Vec<bloxgloom_host_api::generation::Registration>,
    ) -> io::Result<Self> {
        if max_cached_chunks == 0 {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                "cache capacity must be positive",
            ));
        }
        let generator = Arc::new(Generator::new(contributors)?);
        let storage = Storage::with_generation(&path, seed, catalog, &generator)?;
        let sky_ceiling = sky::Ceiling::open(&path, &storage)?;
        let catalog = storage.catalog_arc();
        Ok(Self {
            seed,
            storage,
            catalog,
            generator,
            cache: ChunkCache::new(max_cached_chunks),
            sky_ceiling,
            edit_epochs: HashMap::new(),
            in_flight_by_key: HashMap::new(),
            in_flight_loads: HashMap::new(),
            pending_snapshots: HashMap::new(),
            prepared_revisions: HashMap::new(),
        })
    }

    pub fn catalog_arc(&self) -> Arc<crate::content::Catalog> {
        Arc::clone(&self.catalog)
    }

    /// Independent cache for a loader worker, sharing the already locked
    /// authoritative storage handle. Opening the save again would incorrectly
    /// compete with this world's exclusive writer lock.
    pub(crate) fn loader_view(&self) -> Self {
        Self {
            seed: self.seed,
            storage: self.storage.clone(),
            catalog: Arc::clone(&self.catalog),
            generator: Arc::clone(&self.generator),
            cache: ChunkCache::new(1),
            sky_ceiling: sky::Ceiling::default(),
            edit_epochs: HashMap::new(),
            in_flight_by_key: HashMap::new(),
            in_flight_loads: HashMap::new(),
            pending_snapshots: HashMap::new(),
            prepared_revisions: HashMap::new(),
        }
    }

    #[cfg(test)]
    pub(crate) fn reset_cache_for_test(&mut self, capacity: usize) {
        assert!(capacity > 0);
        assert!(self.in_flight_loads.is_empty());
        assert!(self.pending_snapshots.is_empty());
        self.cache = ChunkCache::new(capacity);
    }

    #[inline]
    pub fn catalog(&self) -> &crate::content::Catalog {
        &self.catalog
    }

    /// Returns an owned, stable snapshot suitable for sending or meshing.
    #[cfg(test)]
    pub fn get_chunk(&mut self, key: ChunkKey) -> io::Result<Chunk> {
        self.ensure_loaded(key)?;
        Ok((*self.cache[&key].read().chunk).clone())
    }

    /// Returns an owned snapshot only when this world already has the chunk in
    /// its authoritative cache. This method never loads or generates terrain.
    pub fn cached_chunk(&mut self, key: ChunkKey) -> Option<Chunk> {
        let entry = self.cache.get_mut_and_touch(key)?;
        Some((*entry.read().chunk).clone())
    }

    /// Borrows the already-resident authoritative chunk for a parallel read
    /// view without copying its voxel array. The Arc pins this exact version
    /// even if a later edit replaces the cached chunk.
    pub fn cached_arc_chunk(&mut self, key: ChunkKey) -> Option<Arc<Chunk>> {
        let entry = self.cache.get_mut_and_touch(key)?;
        Some(Arc::clone(&entry.read().chunk))
    }

    /// Reads the version of an already-resident authoritative chunk without
    /// loading terrain or copying its block array. Phase barriers use this to
    /// reject worker results computed from superseded voxel snapshots.
    #[inline]
    pub fn cached_version(&self, key: ChunkKey) -> Option<u64> {
        self.cache.get(&key).map(|entry| entry.read().chunk.version)
    }

    /// Capture edit authority without pinning a chunk in the cache. The stamp
    /// shares the edit invalidator, including across eviction and reload.
    pub(crate) fn cached_read_stamp(&mut self, key: ChunkKey) -> Option<ChunkReadStamp> {
        self.cache.get(&key)?;
        let (revision, expected_revision) = self.prepared_revision(key);
        Some(ChunkReadStamp {
            revision,
            expected_revision,
        })
    }

    /// Resident chunk count for admission control and server telemetry.
    pub fn resident_chunk_count(&self) -> usize {
        self.cache.len()
    }

    /// Interest subscriptions hold resident owners until every subscriber
    /// leaves or requests a fresh snapshot. No loader may evict these chunks.
    pub(crate) fn pin_resident_chunk(&mut self, key: ChunkKey) -> bool {
        self.cache.pin(key)
    }

    pub(crate) fn unpin_resident_chunk(&mut self, key: ChunkKey) -> bool {
        self.cache.unpin(key)
    }

    pub(crate) fn can_admit_chunk(&self) -> bool {
        self.cache.can_admit()
    }

    /// Reserve cache headroom for distinct asynchronous loads. At capacity,
    /// an in-flight load may consume an unpinned slot, but never a pin.
    pub(crate) fn can_request_chunk(&self, key: ChunkKey) -> bool {
        self.in_flight_by_key.contains_key(&key)
            || self.in_flight_by_key.len()
                < self
                    .cache
                    .capacity()
                    .saturating_sub(self.cache.pinned_len())
    }

    pub(crate) fn pinned_chunk_count(&self) -> usize {
        self.cache.pinned_len()
    }

    /// Resident chunk count for test assertions.
    #[cfg(test)]
    pub fn cached_len(&self) -> usize {
        self.resident_chunk_count()
    }

    /// Reads one block only if its authoritative chunk is resident. `None`
    /// means unavailable, never procedural air; simulation callers must wait
    /// for an asynchronous load instead of inventing collision state.
    #[inline]
    pub fn cached_block(&self, x: i32, y: i32, z: i32) -> Option<BlockId> {
        let (key, local) = world_to_chunk(x, y, z);
        self.cache.get(&key)?.read().chunk.block(local)
    }

    /// Loads and generates without consulting or mutating this world's cache.
    /// Intended for the loader workers, which keep independent `World` values.
    pub fn load_chunk_uncached(&self, key: ChunkKey) -> io::Result<LoadedChunk> {
        let saved = self.storage.load(key)?;
        self.assemble_loaded_chunk(key, saved)
    }

    /// A cloneable storage handle for persistence workers. The caller should
    /// keep its file operations off the simulation tick.
    pub fn storage_handle(&self) -> Storage {
        self.storage.clone()
    }

    /// Capture newer committed checkpoints for a distant worker without registering
    /// gameplay loads or pinning cache entries. The caller fences against commits.
    pub(crate) fn lod_overlays(&self, bounds: [i32; 4]) -> io::Result<Vec<(ChunkKey, Vec<u8>)>> {
        let mut result = Vec::new();
        let mut bytes = 0usize;
        for (&key, snapshot) in &self.pending_snapshots {
            let x = i64::from(key.x) * CHUNK_SIZE as i64;
            let z = i64::from(key.z) * CHUNK_SIZE as i64;
            if x >= i64::from(bounds[0])
                && x < i64::from(bounds[2])
                && z >= i64::from(bounds[1])
                && z < i64::from(bounds[3])
            {
                let snapshot = snapshot.clone().unwrap_or_default();
                bytes += snapshot.len();
                if bytes > 4 * 1024 * 1024 || result.len() >= 4096 {
                    return Err(io::Error::other("LOD committed overlay budget exceeded"));
                }
                result.push((key, snapshot));
            }
        }
        Ok(result)
    }

    /// The current per-key load epoch. Epoch entries are retained only while
    /// loads are in flight, so exploration does not grow a permanent map.
    pub fn edit_epoch(&self, key: ChunkKey) -> u64 {
        self.edit_epochs.get(&key).copied().unwrap_or(0)
    }

    /// Registers an asynchronous load and returns its per-key epoch plus any
    /// newer journal snapshot that has not reached the BGED file yet.
    pub fn begin_chunk_load(&mut self, key: ChunkKey) -> io::Result<(u64, Option<Vec<u8>>)> {
        let epoch = self.edit_epoch(key);
        let count = self
            .in_flight_loads
            .get(&(key, epoch))
            .copied()
            .unwrap_or(0);
        let key_count = self.in_flight_by_key.get(&key).copied().unwrap_or(0);
        let next_count = count
            .checked_add(1)
            .ok_or_else(|| io::Error::other("chunk load count exhausted"))?;
        let next_key_count = key_count
            .checked_add(1)
            .ok_or_else(|| io::Error::other("chunk load count exhausted"))?;
        self.in_flight_loads.insert((key, epoch), next_count);
        self.in_flight_by_key.insert(key, next_key_count);
        let pending = self
            .pending_snapshots
            .get(&key)
            .map(|snapshot| snapshot.clone().unwrap_or_default());
        Ok((epoch, pending))
    }

    /// Retires a registered request after its result is installed, rejected,
    /// or fails. This bounds epoch bookkeeping by outstanding load work.
    pub fn finish_chunk_load(&mut self, key: ChunkKey, epoch: u64) {
        let retired = if let Some(count) = self.in_flight_loads.get_mut(&(key, epoch)) {
            *count -= 1;
            if *count == 0 {
                self.in_flight_loads.remove(&(key, epoch));
            }
            true
        } else {
            false
        };
        if !retired {
            return;
        }
        if let Some(count) = self.in_flight_by_key.get_mut(&key) {
            *count -= 1;
            if *count == 0 {
                self.in_flight_by_key.remove(&key);
                self.edit_epochs.remove(&key);
            }
        }
    }

    /// Builds a loaded chunk from a captured BGED snapshot without file I/O.
    /// An empty snapshot is the generated baseline.
    pub fn load_chunk_snapshot_uncached(
        &self,
        key: ChunkKey,
        snapshot: &[u8],
    ) -> io::Result<LoadedChunk> {
        let saved = self
            .storage
            .decode_snapshot((!snapshot.is_empty()).then_some(snapshot))?;
        self.assemble_loaded_chunk(key, saved)
    }

    /// Installs a worker result only when this key is still absent and has not
    /// been edited since the request captured `expected_edit_epoch`.
    pub fn install_loaded_if_absent(
        &mut self,
        loaded: LoadedChunk,
        expected_edit_epoch: u64,
    ) -> io::Result<bool> {
        let key = loaded.chunk.key;
        if loaded.chunk.blocks.len() != CHUNK_VOLUME
            || loaded
                .chunk
                .blocks
                .iter()
                .any(|&block| self.catalog.state(block).is_none())
            || loaded.edits.iter().any(|(&index, &block)| {
                index as usize >= CHUNK_VOLUME || self.catalog.state(block).is_none()
            })
        {
            self.finish_chunk_load(key, expected_edit_epoch);
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                "invalid loaded chunk result",
            ));
        }
        let eligible =
            !self.cache.contains_key(&key) && self.edit_epoch(key) == expected_edit_epoch;
        let installed = eligible && self.cache_loaded_chunk(loaded);
        self.finish_chunk_load(key, expected_edit_epoch);
        Ok(installed)
    }

    /// Reads the exact persisted override snapshot for journal comparisons.
    pub fn read_chunk_snapshot(&self, key: ChunkKey) -> io::Result<Option<Vec<u8>>> {
        if let Some(snapshot) = self.pending_snapshots.get(&key) {
            return Ok(snapshot.clone());
        }
        self.storage.read_snapshot(key)
    }

    /// Clears a journal-backed snapshot marker after a storage worker has
    /// atomically checkpointed the matching BGED bytes. Does no disk I/O.
    pub fn clear_checkpointed_snapshot(&mut self, key: ChunkKey, snapshot: &[u8]) -> bool {
        if self
            .pending_snapshots
            .get(&key)
            .is_some_and(|pending| pending.as_deref().unwrap_or_default() == snapshot)
        {
            self.pending_snapshots.remove(&key);
            true
        } else {
            false
        }
    }

    /// Validates and restores one committed BGED snapshot during journal replay.
    /// The write is atomic, and a cached copy is refreshed if it exists.
    pub fn restore_snapshot(&mut self, key: ChunkKey, snapshot: &[u8]) -> io::Result<()> {
        let value = (!snapshot.is_empty()).then_some(snapshot);
        let existing = self.storage.read_snapshot(key)?;
        self.storage.decode_snapshot(existing.as_deref())?;
        let saved = self.storage.decode_snapshot(value)?;
        let loaded = self.assemble_loaded_chunk(key, saved)?;
        self.bump_edit_epoch(key)?;
        self.advance_prepared_revision(key)?;
        if let Err(error) = self.storage.replace_snapshot(key, value) {
            self.cache.remove(&key);
            return Err(error);
        }
        self.pending_snapshots.remove(&key);
        self.sky_ceiling.update(key, !loaded.edits.is_empty());
        if let Some(entry) = self.cache.get_mut(&key) {
            let mut state = entry.write();
            state.chunk = Arc::new(loaded.chunk);
            state.edits = loaded.edits;
        }
        Ok(())
    }

    pub fn get_block(&mut self, x: i32, y: i32, z: i32) -> io::Result<BlockId> {
        let (key, local) = world_to_chunk(x, y, z);
        self.ensure_loaded(key)?;
        Ok(self.cache[&key].read().chunk.block(local).unwrap())
    }

    /// A successful return means the changed block and version have been saved.
    #[cfg(test)]
    pub fn edit(&mut self, x: i32, y: i32, z: i32, block: BlockId) -> io::Result<(ChunkKey, u64)> {
        let (key, _) = world_to_chunk(x, y, z);
        self.ensure_loaded(key)?;
        let prepared = self.prepare_edit(x, y, z, block)?;
        if !prepared.changed {
            return Ok((prepared.key, prepared.new_version));
        }
        if self.in_flight_by_key.contains_key(&key) && self.edit_epoch(key) == u64::MAX {
            return Err(io::Error::other("chunk load epoch exhausted"));
        }
        if prepared.revision.load(Ordering::Acquire) == u64::MAX {
            return Err(io::Error::other("prepared edit revision exhausted"));
        }
        let saved = self.storage.decode_snapshot(
            (!prepared.after_snapshot.is_empty()).then_some(prepared.after_snapshot.as_slice()),
        )?;
        if let Err(error) = self.storage.save(key, &saved) {
            // The rename may have succeeded before a directory-sync error.
            // Invalidate requests and reload from disk on next access.
            self.bump_edit_epoch(key)?;
            self.advance_prepared_revision(key)?;
            self.cache.remove(&key);
            return Err(error);
        }
        self.apply_prepared_edit_inner(prepared, false)
    }

    /// Prepares an edit from the authoritative cache only. Missing chunks are
    /// reported as WouldBlock so server tick code can wait for a loader result.
    #[cfg(test)]
    pub fn prepare_edit(
        &mut self,
        x: i32,
        y: i32,
        z: i32,
        block: BlockId,
    ) -> io::Result<PreparedEdit> {
        let edits = self.prepare_edits(&[(x, y, z, block)])?;
        Ok(edits
            .into_iter()
            .next()
            .expect("one input targets one chunk"))
    }

    /// Prepares a multi-block edit as one versioned snapshot per touched chunk.
    /// Every target must already be in the authoritative cache.
    pub fn prepare_edits(
        &mut self,
        edits: &[(i32, i32, i32, BlockId)],
    ) -> io::Result<Vec<PreparedEdit>> {
        let mut grouped: HashMap<ChunkKey, Vec<(u16, BlockId)>> = HashMap::new();
        let mut coordinates = HashSet::with_capacity(edits.len());
        for &(x, y, z, block) in edits {
            if self.catalog.state(block).is_none() {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidInput,
                    "unknown block identifier",
                ));
            }
            if y <= BEDROCK_Y {
                return Err(io::Error::new(
                    io::ErrorKind::PermissionDenied,
                    "world bottom is immutable",
                ));
            }
            if !coordinates.insert((x, y, z)) {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidInput,
                    "duplicate coordinate in prepared edits",
                ));
            }
            let (key, local) = world_to_chunk(x, y, z);
            let index =
                Chunk::index(local).expect("world_to_chunk returns local coordinates") as u16;
            grouped.entry(key).or_default().push((index, block));
        }

        let mut keys: Vec<_> = grouped.keys().copied().collect();
        keys.sort_by_key(|key| (key.x, key.y, key.z));
        let mut prepared = Vec::with_capacity(keys.len());
        for key in keys {
            let basis = self.cached_edit_basis(key).ok_or_else(|| {
                io::Error::new(
                    io::ErrorKind::WouldBlock,
                    "chunk is not in the authoritative cache",
                )
            })?;
            prepared.push(basis.prepare_sparse(&grouped[&key])?);
        }
        Ok(prepared)
    }

    /// Freeze one resident authoritative chunk for a worker-owned edit plan.
    /// A cache miss is explicit; no worker generates a substitute baseline.
    pub(crate) fn cached_edit_basis(&mut self, key: ChunkKey) -> Option<Arc<EditBasis>> {
        let entry = self.cache.get(&key)?;
        let state = entry.read();
        let chunk = Arc::clone(&state.chunk);
        let edits = state.edits.clone();
        drop(state);
        let (revision, expected_revision) = self.prepared_revision(key);
        Some(Arc::new(EditBasis {
            key,
            chunk,
            edits,
            seed: self.seed,
            storage: self.storage.clone(),
            catalog: Arc::clone(&self.catalog),
            generator: Arc::clone(&self.generator),
            revision,
            expected_revision,
        }))
    }

    /// Applies a WAL-synced edit to memory without writing the BGED snapshot.
    /// The pending snapshot remains authoritative across cache eviction until a
    /// successful checkpoint clears it.
    #[cfg(test)]
    pub fn apply_prepared_edit(&mut self, prepared: PreparedEdit) -> io::Result<(ChunkKey, u64)> {
        let mut applied = self.apply_prepared_edits(vec![prepared])?;
        Ok(applied.pop().expect("single prepared edit"))
    }

    /// Atomically validates and applies one prepared snapshot per chunk in
    /// memory. It performs no disk I/O and records overlays until checkpointed.
    pub fn apply_prepared_edits(
        &mut self,
        prepared: Vec<PreparedEdit>,
    ) -> io::Result<Vec<(ChunkKey, u64)>> {
        let mut keys = HashSet::with_capacity(prepared.len());
        for edit in &prepared {
            if !keys.insert(edit.key) {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidInput,
                    "duplicate chunk in prepared edits",
                ));
            }
            self.validate_prepared_edit(edit)?;
            if edit.changed
                && self.in_flight_by_key.contains_key(&edit.key)
                && self.edit_epoch(edit.key) == u64::MAX
            {
                return Err(io::Error::other("chunk load epoch exhausted"));
            }
            if edit.changed && edit.revision.load(Ordering::Acquire) == u64::MAX {
                return Err(io::Error::other("prepared edit revision exhausted"));
            }
        }

        let mut versions = Vec::with_capacity(prepared.len());
        for edit in prepared {
            versions.push((edit.key, edit.new_version));
            self.apply_prepared_edit_inner(edit, true)?;
        }
        Ok(versions)
    }

    fn apply_prepared_edit_inner(
        &mut self,
        prepared: PreparedEdit,
        keep_pending_snapshot: bool,
    ) -> io::Result<(ChunkKey, u64)> {
        let key = prepared.key;
        self.validate_prepared_edit(&prepared)?;
        if !prepared.changed {
            return Ok((key, prepared.new_version));
        }

        self.bump_edit_epoch(key)?;
        self.advance_prepared_revision(key)?;
        if keep_pending_snapshot {
            self.pending_snapshots.insert(
                key,
                (!prepared.after_snapshot.is_empty()).then_some(prepared.after_snapshot.clone()),
            );
        } else {
            self.pending_snapshots.remove(&key);
        }
        if !self.cache_loaded_chunk(LoadedChunk {
            chunk: prepared.after_chunk,
            edits: prepared.after_edits,
        }) {
            return Err(io::Error::other(
                "WAL-synced chunk could not enter a fully subscribed cache",
            ));
        }
        Ok((key, prepared.new_version))
    }

    fn validate_prepared_edit(&self, prepared: &PreparedEdit) -> io::Result<()> {
        if prepared.revision.load(Ordering::Acquire) != prepared.expected_revision {
            return Err(io::Error::new(
                io::ErrorKind::WouldBlock,
                "prepared edit was invalidated by a newer chunk edit",
            ));
        }
        // Load epochs are only for rejecting stale loader results. They may
        // reset to zero when the last load completes, even while a WAL-backed
        // edit is pending. The Arc revision above tracks actual edits across
        // eviction and is the authoritative prepared-edit invalidator.
        if let Some(entry) = self.cache.get(&prepared.key) {
            let state = entry.read();
            if state.chunk.version != prepared.expected_version
                || state.edits != prepared.before_edits
            {
                return Err(io::Error::new(
                    io::ErrorKind::WouldBlock,
                    "prepared edit no longer matches the authoritative chunk",
                ));
            }
        }
        Ok(())
    }

    /// Number of journal-backed chunk snapshots waiting for a successful
    /// BGED checkpoint; useful for observable persistence backpressure.
    pub fn pending_snapshot_count(&self) -> usize {
        self.pending_snapshots.len()
    }

    fn prepared_revision(&mut self, key: ChunkKey) -> (Arc<AtomicU64>, u64) {
        self.prepared_revisions
            .retain(|_, revision| revision.strong_count() > 0);
        let revision = self
            .prepared_revisions
            .get(&key)
            .and_then(Weak::upgrade)
            .unwrap_or_else(|| {
                let revision = Arc::new(AtomicU64::new(0));
                self.prepared_revisions
                    .insert(key, Arc::downgrade(&revision));
                revision
            });
        let value = revision.load(Ordering::Acquire);
        (revision, value)
    }

    fn advance_prepared_revision(&mut self, key: ChunkKey) -> io::Result<()> {
        self.prepared_revisions
            .retain(|_, revision| revision.strong_count() > 0);
        let Some(revision) = self.prepared_revisions.get(&key).and_then(Weak::upgrade) else {
            self.prepared_revisions.remove(&key);
            return Ok(());
        };
        revision
            .fetch_update(Ordering::AcqRel, Ordering::Acquire, |value| {
                value.checked_add(1)
            })
            .map(|_| ())
            .map_err(|_| io::Error::other("prepared edit revision exhausted"))
    }

    fn bump_edit_epoch(&mut self, key: ChunkKey) -> io::Result<u64> {
        if !self.in_flight_by_key.contains_key(&key) {
            return Ok(self.edit_epoch(key));
        }
        let next = self
            .edit_epoch(key)
            .checked_add(1)
            .ok_or_else(|| io::Error::other("chunk load epoch exhausted"))?;
        self.edit_epochs.insert(key, next);
        Ok(next)
    }

    fn assemble_loaded_chunk(&self, key: ChunkKey, saved: SavedEdits) -> io::Result<LoadedChunk> {
        let mut chunk = self.generator.generate(key, self.seed, &self.catalog)?;
        for (&index, &block) in &saved.blocks {
            chunk.blocks.set(index as usize, block);
        }
        chunk.version = saved.version;
        Ok(LoadedChunk {
            chunk,
            edits: saved.blocks,
        })
    }

    fn cache_loaded_chunk(&mut self, loaded: LoadedChunk) -> bool {
        let key = loaded.chunk.key;
        let edited = !loaded.edits.is_empty();
        let installed = self.cache.insert(key, Arc::new(loaded.chunk), loaded.edits);
        if installed {
            self.sky_ceiling.update(key, edited);
        }
        installed
    }

    fn ensure_loaded(&mut self, key: ChunkKey) -> io::Result<()> {
        if self.cache.get_mut_and_touch(key).is_some() {
            return Ok(());
        }
        let loaded = if let Some(snapshot) = self.pending_snapshots.get(&key) {
            let saved = self.storage.decode_snapshot(snapshot.as_deref())?;
            self.assemble_loaded_chunk(key, saved)?
        } else {
            self.load_chunk_uncached(key)?
        };
        if !self.cache_loaded_chunk(loaded) {
            return Err(io::Error::new(
                io::ErrorKind::WouldBlock,
                "all resident chunks are subscribed",
            ));
        }
        Ok(())
    }
}

#[cfg(test)]
#[path = "world/tests.rs"]
mod tests;
